### ISSUE TITLE
kafka-backup and older versions of Kafka

### ISSUE THREAD

**Issue by apopaa** [itadventurer/kafka-backup#102]
Can kafka-backup be used to back up and restore older version of Kafka brokers? Let's say my Kafka cluster is made up of brokers running Kafka 2.3.1. Can I use kafka-backup to back up this cluster, and restore it to another, Kafka 2.3.1 cluster? Do I need to install/update/upgrade any component of my Kafka 2.3.1 cluster(s)?

The current documentation is not very clear, some mentions Kafka 2.3.0 and some requires Kafka 2.4.0.

Thanks,
Andrei Popa

**Comment by itadventurer** [comment]
You need Kafka >=2.4 to be able to restore the offsets. You can do a backup with Kafka 2.3.

**Comment by apopaa** [comment]
Right. Thanks.
Just to be clear: the Kafka server has to be 2.4, where I'm restoring the backup. Right?
I can backup a Kafka 2.3 server, but if I restore the backup onto a Kafka 2.3 server the offsets won't be right. For that, I will need to restore onto a Kafka 2.4 server.

Thank you,
Andrei Popa

**Comment by itadventurer** [comment]
exactly
