### ISSUE TITLE
Cannot find the kafka-backup.jar in .. Please set --backup-jar accordingly

### ISSUE THREAD

**Issue by nmadmon** [itadventurer/kafka-backup#103]
Hi, 
Itry to execute the backup script and I got an error:

[kafka@ip-172-31-11-225 bin]$ ./backup-standalone.sh --bootstrap-server localhost:9092 --target-dir /home/kafka/backup --topics 'BackupTopic'
Cannot find the kafka-backup.jar in .. Please set --backup-jar accordingly

I failed to find it under kafka and under your tool. 

Can you help me?

**Comment by Damasker** [comment]
If you build from source, you can find jar in build/libs folder.
Or download binary from https://github.com/itadventurer/kafka-backup/releases
Then just copy kafka-backup.jar to bin/
