### ISSUE TITLE
Support for latest KAFKA

### ISSUE THREAD

**Issue by wrahmann** [itadventurer/kafka-backup#124]
Hi,

Can you confirm if KAFKA backup has compatibility with the specific KAFKA version or it can be used with the latest KAFKA releases? 

Is there any deployment script or helm chart that can be used to deploy it on the Kubernetes cluster?

Regards,

**Comment by itadventurer** [comment]
Hi,
I am currently not able to maintain this Project on my own. If you are interested in supporting me, please let me know.
