### ISSUE TITLE
A few Question's for connecting

### ISSUE THREAD

**Issue by jessetandor** [itadventurer/kafka-backup#125]
Hi, 

Nice tool you have here, i have a few questions though: 

I've populated the initial connection vars in the backup-standalone.sh script :

```
> [ -z ${BOOTSTRAP_SERVER+x} ] && BOOTSTRAP_SERVER="172.17.0.1"
> [ -z ${TARGET_DIR+x} ] && TARGET_DIR="/var/lib/kafka/backup"
> [ -z ${TOPICS+x} ] && TOPICS="mytopic.test"
> [ -z ${TOPICS_REGEX+x} ] && TOPICS_REGEX=""
> [ -z ${MAX_SEGMENT_SIZE+x} ] && MAX_SEGMENT_SIZE="$((1 * 1024 * 1024 * 1024))" # 1GiB
> [ -z ${COMMAND_CONFIG+x} ] && COMMAND_CONFIG="/tmp/jaas.config"
> [ -z ${DEBUG+x} ] && DEBUG="n"
```

When running it, do I still need to specify --command-config /tmp/jaas.config ?

I've set up the backup-sink, but I'm unsure how to enable it. The path of the kafka-backup.jar file is already enabled in my 'connect-standalone.properties' file and Kafka is restarted just in case.
`plugin.path=/opt/kafka/bin/plugins`

How can I enable it?  This doesn't work:
```
curl -X POST -H "Content-Type: application/json" \
  --data "/opt/kafka/config/connect-backup-sink.properties"
  http://my.connect.server:8083/connectors
```

What's the significance of 'http://my.connect.server:8083/connectors' and what is the expected result from the command?

Contents of backup-sink are defaults from the doc's.

**Comment by itadventurer** [comment]
Please check the Kafka Connect documentation here: https://kafka.apache.org/documentation/#connect

This project is currently on hold as I do not have the time to contribute to it further.
