### ISSUE TITLE
Optional.isEmpty() error when using Java8 included in cp-ansible v5.4 kafka connect

### ISSUE THREAD

**Issue by gstuder-ona** [itadventurer/kafka-backup#13]
I noticed that the connector was failing with kafka deployed using the standard deployment of cp-ansible (https://github.com/confluentinc/cp-ansible) at version 5.4 - seems like the provisioned java version (8) is lower than expected here.

The simple fix to use !isPresent() in SegmentReader.java?  From the docs here: https://docs.confluent.io/current/installation/versions-interoperability.html it seems like Java8 is a supported jvm for the 5.4 series, so it may be most-compatible to match that?

**Comment by itadventurer** [comment]
Thank you for this but, too! Yes that should fix that. Again: feel free to
open a PR for that. Otherwise I will try to fix the issue in the next days
-- 
Viele Grüße,
Anatoly Zelenin
