### ISSUE TITLE
Restoring multi-partition topic

### ISSUE THREAD

**Issue by alexk2000** [itadventurer/kafka-backup#32]
I am not sure if it's an issue, maybe I missed something in connect-backup-source.properties.
When I restore topic with 24 partitions it creates topic with one partitions and restore failed.
Restore successful if I create 24 partitions topic before restore.

Have I missed something or multi-partition topic creation not supported so far ?

**Comment by itadventurer** [comment]
You need to create the topic manually before restore. I will add this to the FAQ Issue.

**Comment by itadventurer** [comment]
Basically, for a "real" backup scenario you also need to backup and restore Zookeeper. Again, currently there is not really a documentation for that, you can find some pointers in the scripts here: [system_test/backup_with_burry](https://github.com/itadventurer/kafka-backup/tree/master/system_test/backup_with_burry)

**Comment by alexk2000** [comment]
I see, thank you.
