### ISSUE TITLE
Document how to cleanup old segments when doing a backup

### ISSUE THREAD

**Issue by itadventurer** [itadventurer/kafka-backup#42]
A usual setup is to have Kafka Backup running continuously in the background which writes data to the local disk.
Then, in parallel a CronJob will move the data to the target backup storage. Afterwards it is possible to delete old segments and indexes. (NOT the current ones)
We should document how to do that gracefully. (Maybe even provide a script for that)

**Comment by jay7x** [comment]
Was it done btw?

**Comment by itadventurer** [comment]
Yes! Good point. Solved by #90
