### ISSUE TITLE
Can we shutdown Kafka Connect after Restore has finished?

### ISSUE THREAD

**Issue by itadventurer** [itadventurer/kafka-backup#46]

**Comment by akamensky** [comment]
I still think backup should also be just like a snapshot of data, thus once the snapshot is complete the backup process would exit. Just as I mentioned in #52 (please see last added comment for use-case/reasoning).

To add -- RDBMS can also be seen as a continuous stream of data (stored in relational form), but nevertheless it allows for a momentary snapshot of data via backup tools, which is considered pretty normal there, why should it be different in case of Kafka.

There are other tools that provide "continuous backup" via replication to another cluster. That does not satisfy all use cases, I think that is where this tool could be useful -- allow for momentary snapshots of data disregarding any new messages arriving after the backup has started (same as RDBMS backup would work).

**Comment by itadventurer** [comment]
This issue is for the restore procedure as there is a clear path how to stop it. See my comments in #52 for doing snapshot backups ;)

**Comment by itadventurer** [comment]
This issue is fixed with #56. See #52 for the backup-side
