### ISSUE TITLE
Please publish binary releases

### ISSUE THREAD

**Issue by akamensky** [itadventurer/kafka-backup#51]
This is intended as a tool, so please publish binary release, it is not fun trying to compile code every time I would like to use it.

**Comment by itadventurer** [comment]
I absolutely agree with you! I have created a new milestone for v0.1 and added it there.

**Comment by itadventurer** [comment]
There will be two kinds of "binary" releases:

* Docker images pushed to Dockerhub
* zip/tar.gz files containing the CLI tools and the built jar files
