### ISSUE TITLE
build/compile errors

### ISSUE THREAD

**Issue by prasus** [itadventurer/kafka-backup#6]
`./gradlew shadowJar` results in the below error for me 😞 

Appreciate it if you could provide some pointers on fixing this issue, Also do we have any pre-built docker image for `kafka-backup`? Thanks 🙏 

``` 
./gradlew shadowJar

> Task :compileJava FAILED
/Users/prasadzone/kafka-backup/src/main/java/de/azapps/kafkabackup/common/segment/SegmentReader.java:49: error: cannot find symbol
        if (optionalPosition.isEmpty()) {
                            ^
  symbol:   method isEmpty()
  location: variable optionalPosition of type Optional<Long>
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

**Comment by itadventurer** [comment]
Hi,
This seems to be an issue with your build environment. Somehow your environment cannot find `Optional.isEmpty` – which Java version do you use?
Sometimes IntelliJ has problems with `Optional`. See here how to solve that: https://stackoverflow.com/questions/25205625/intellij-cannot-find-java-util-optional

**Comment by prasus** [comment]
Thank you @itadventurer I am on Java 8 and was able to solve this by referring to the post above.
