### ISSUE TITLE
Adding a restore to different destination topic

### ISSUE THREAD

**Issue by cschellenbach** [itadventurer/kafka-backup#65]
Hello,

I didn't see in the documentation if it's possible to be able to restore to a different destination topic, such as mybackupedtopic-restored. It would help with testing restore procedures without disturbing the existing topic, among other things. 

Thanks,

Chris

**Comment by itadventurer** [comment]
Hi Chris,
No, currently there is no direct support for that :thinking: But you can simply rename the directories of the topic and configure the restore procedure accordingly.

This is a good point to add to the (currently non-existing) FAQ but I do not think this should be implemented in Code.

**Comment by cschellenbach** [comment]
Works for me. It's good to put what mechanism actually determines what the destination is, and in this case it seems to be the directory name. Thanks for looking into this quickly.

**Comment by cschellenbach** [comment]
I tested this and it worked. Thanks for the tip!
