### ISSUE TITLE
Restore issues

### ISSUE THREAD

**Issue by akamensky** [itadventurer/kafka-backup#83]
I am trying to restore data and seeing following issues:

1. Missing `cluster.[key|value|header].deserializer` configs
2. `[2020-04-28 18:35:21,628] WARN [Producer clientId=connector-producer-backup-source-0] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient:1031)`
3. Never showed message `All records read. Restore was successful`
4. ```[2020-04-28 18:35:32,201] ERROR WorkerSourceTask{id=backup-source-0} Failed to flush, timed out while waiting for producer to flush outstanding 1 messages (org.apache.kafka.connect.runtime.WorkerSourceTask:438) [2020-04-28 18:35:32,202] ERROR WorkerSourceTask{id=backup-source-0} Failed to commit offsets (org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter:114)```

**Comment by akamensky** [comment]
FWIW - we have authentication enabled in our cluster. It is authentication to ZK/interbroker/client. client auth is SCRAM-SHA-256 (SASL_PLAINTEXT)

**Comment by itadventurer** [comment]
Hi,
Are you using the new restore-standalone.sh tool? That should help you with the issues. You can simply add the SASL credentials via the `--command-config` argument.

If not, please provide the config you are using.

**Comment by itadventurer** [comment]
I assume this is fixed ;)
