### ISSUE TITLE
Housekeeping 'online' backup directory

### ISSUE THREAD

**Issue by jay7x** [itadventurer/kafka-backup#89]
So I enabled kafka-backup on our production cluster and got 96Gb of data there.
Then I stopped kafka-backup and synced it to Azure blobstore for long-term storage. What files can I drop from backup directory safely after?

Let's say I have these files in my backup directory for topic `peercomparison`:
```
peercomparison/segment_partition_000_from_offset_0000000000_records
peercomparison/segment_partition_000_from_offset_0006444512_records
peercomparison/segment_partition_000_from_offset_0006760591_records
peercomparison/segment_partition_001_from_offset_0000000000_records
peercomparison/segment_partition_001_from_offset_0006443675_records
peercomparison/segment_partition_001_from_offset_0006760356_records
peercomparison/segment_partition_002_from_offset_0000000000_records
peercomparison/segment_partition_002_from_offset_0006561069_records
peercomparison/segment_partition_002_from_offset_0006890641_records
peercomparison/segment_partition_003_from_offset_0000000000_records
peercomparison/segment_partition_003_from_offset_0006420355_records
peercomparison/segment_partition_003_from_offset_0006741837_records
peercomparison/segment_partition_004_from_offset_0000000000_records
peercomparison/segment_partition_004_from_offset_0006547151_records
peercomparison/segment_partition_004_from_offset_0006870528_records
```

I guess I can safely delete every non-latest file in this directory, right?
e.g. files from list below can be deleted safely for partition 000:
```
peercomparison/segment_partition_000_from_offset_0000000000_records
peercomparison/segment_partition_000_from_offset_0006444512_records
```

**Comment by itadventurer** [comment]
You need the following files:

* The latest `*_records` file for each partition
* The corresponding (latest) `*_index` file for each partition
* The `index_partition_*` file for each partition

Would you mind to try it out and write a short step-by-step guide how you did that? I think that would be very helpful for other users ;)

**Comment by jay7x** [comment]
I'm heading to write script to cleanup instead :)
