### ISSUE TITLE
release 0.1.1 broken

### ISSUE THREAD

**Issue by carlobongiovanni** [itadventurer/kafka-backup#94]
Hi, I noticed that the release v0.1.1 published in github has a broken link of kafka-backup.jar:

tree of bin folder of v0.1.1:
```
# cbongiovanni @ LM-TXL-14511286 in ~/Downloads/kafka-backup-0.1.1 [13:36:20]
$ tree bin
bin
├── backup-standalone.sh
├── kafka-backup.jar -> ../build/libs/kafka-backup.jar
├── partition-index.sh
├── restore-standalone.sh
├── segment-index.sh
└── segment.sh

0 directories, 6 files
```
this link doesn't exists: kafka-backup.jar -> ../build/libs/kafka-backup.jar

while the tree of the first release is completely different
```
# cbongiovanni @ LM-TXL-14511286 in ~/Downloads/kafka-backup 2 [13:38:12]
$ tree .
.
├── backup-standalone.sh
├── kafka-backup.jar
├── partition-index.sh
├── restore-standalone.sh
├── segment-index.sh
└── segment.sh

0 directories, 6 files
```

**Comment by itadventurer** [comment]
Hi,
Yeah, I removed the jar file from the git repository. You need to download the release asset and not the source code. (Or build it yourself..). Have a look at the readme: https://github.com/itadventurer/kafka-backup#getting-started
